export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SEARCH_ALL = "SEARCH_ALL";
export const SEARCH_CATEGORIE = "SEARCH_CATEGORIE";
export const SEARCH_GENDER = "SEARCH_GENDER";
export const INPUT_SEARCH = "INPUT_SEARCH";

export const USER_LOADED = "USER_LOADED";
export const ALL_USERS = "ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const ADD_PROFILE_TO_DB = "ADD_PROFILE_TO_DB";

export const ADD_ARTICLE_TO_CART = "ADD_ARTICLE_TO_CART";
export const UPDATE_CART_ARTICLE = "UPDATE_CART_ARTICLE";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";

export const CLEAR_CART_STATE = "CLEAR_CART_STATE";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const CLEAR_ALL_CART_ARTICLES = "CLEAR_ALL_CART_ARTICLES";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const MODIFY_PRODUCT = "MODIFY_PRODUCT";

export const SET_ALERT = "SET_ALERT";
export const DISPLAY_ALERT = "DISPLAY_ALERT";

